apiVersion: v1

kind: Pod

metadata:
  name: container-port
  labels:
    app: nginx_p
    tier: front-end
    
spec:
  containers:
    - name: nginxc
      image: nginx
      ports:
        - containerPort: 80
    - name: busyboxc
      image: busybox/latest
      command: ["/bin/bash"]
      args: ["-c", "while true; do echo 'Hello World!'; sleep 20; done"]
